import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import {SliderData} from '../components/SliderData'
import Slider from '../components/Slider'
import ImageContent from '../images/slider1.jpg'
import Instagram from '../components/instagram'

export default function Home() {
  return (
    <>
      <Head>
        <title>iWealth Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
      </div>
      <Hero title ='iWealth Captur Photography' message='I capture moments in nature and keep them alive'/>
      <Slider slides = {SliderData}/>
      <Instagram/>
    </>
  )
}
